"""inital

Revision ID: 7b1b3e68bdf1
Revises:
Create Date: 2023-09-29 02:03:51.405539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1b3e68bdf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=30), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('avatar_url', sa.Text(), nullable=True),
        sa.Column('city', sa.String(length=50), nullable=True),
        sa.Column('age', sa.SmallInteger(), nullable=True),
        sa.Column('gender', sa.String(length=15), nullable=True),
        sa.Column('is_email_public', sa.Boolean(), nullable=True),
        sa.Column('github', sa.String(length=128), nullable=True),
        sa.Column('is_github_public', sa.Boolean(), nullable=True),
        sa.Column('discord', sa.String(length=128), nullable=True),
        sa.Column('is_discord_public', sa.Boolean(), nullable=True),
        sa.Column('skill', sa.Text(), nullable=True),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table(
        'project',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('host_user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('max_member_number', sa.SmallInteger(), nullable=True),
        sa.Column('current_member_number', sa.SmallInteger(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('intro', sa.String(length=50), nullable=True),
        sa.Column('desc', sa.Text(), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=True),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['host_user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
