"""add topic table

Revision ID: 90edfd99fc44
Revises: 26600b533db6
Create Date: 2023-11-15 19:18:54.800217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90edfd99fc44'
down_revision: Union[str, None] = '26600b533db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'topic',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_topic_id'), 'topic', ['id'], unique=False)
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=True)
    op.create_table(
        'project_topic_intermediay',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('topic_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.id'],
        ),
        sa.ForeignKeyConstraint(
            ['topic_id'],
            ['topic.id'],
        ),
        sa.PrimaryKeyConstraint('project_id', 'topic_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_topic_intermediay')
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_index(op.f('ix_topic_id'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
