name: Run Pytest
on:
  push:
    branches:
      - dev
      - main

  pull_request:

env:
  JWT_SECRET_KEY: test_key

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip

      - name: Install dependencies
        run: |
          cd ./backend
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

      - name: Run test
        run: |
          cd ./backend
          python -B -m pytest
